### ISSUE TITLE
Out of date stats aren't always updated

### ISSUE THREAD

**Issue by dandenton** [yochananrachamim/AzureSQL#11]
Statistics aren't being updated if they belong to an index that wasn't updated. In the section with the comment `Remove statistics if it is handled by index rebuild / reorganize` the script removes stats that exist in `#idxBefore` but that includes all indexes, not just the ones that are being rebuilt.  It should probably include the same where clause and/or delete records from `#idxBefore` that aren't being updated.

This was the change we made locally to fix the issue:
![image](https://user-images.githubusercontent.com/56007134/93362880-c613d400-f803-11ea-91f4-3d1cdfc10ab1.png)

**Comment by yochananrachamim** [comment]
Fixed.
