### ISSUE TITLE
Heaps and Forwarded Records

### ISSUE THREAD

**Issue by kfrancis** [yochananrachamim/AzureSQL#12]
Love the script, been working so well but we hit an issue today with heaps and forwarded records:

https://www.brentozar.com/archive/2016/07/fix-forwarded-records/

There's some discussion in there about this: https://github.com/olahallengren/sql-server-maintenance-solution/issues/48

and it looks like you're similarly ignoring heaps in your script as well.

**Comment by yochananrachamim** [comment]
This is now added to the procedure. I hope you will find it useful.
