### ISSUE TITLE
Question: How does this compare to Automatic Tuning now available for Azure SQL?

### ISSUE THREAD

**Issue by isamllr** [yochananrachamim/AzureSQL#7]
Hi Yochanan,
Question: How does this compare to Automatic Tuning now available for Azure SQL? Can it be used along side? Anything to be careful about if used with geo-replicas and read-only secondaries?

https://docs.microsoft.com/en-us/sql/relational-databases/automatic-tuning/automatic-tuning?view=azuresqldb-current

**Comment by vytux-com** [comment]
They are completely different things. Automatic tuning suggests which indexes to create and delete. This project maintains existing indexes (including those created by Auto tuning suggestions)
